---
# This will create the NS for our demo
apiVersion: v1
kind: Namespace
metadata:
  name: conjur
---
# This ServiceAccount provides the Kubernetes RBAC identity for the Conjur Kubernetes authenticator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur-demo-acct
  namespace: conjur
---
# This Role defines the Kubernetes API access permissions that the Conjur
# authenticator will require in order to validate application identities.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: conjur-role
  namespace: conjur
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "serviceaccounts"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
# The Authenticator RoleBinding grants permissions to the Conjur Authenticator ServiceAccount
# for the authenticator Role, which provides a list of Kubernetes API access permissions.
# This is required to validate application identities.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conjur-role
  namespace: conjur
subjects:
- kind: ServiceAccount
  name: conjur-demo-acct
  namespace: conjur
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: conjur
---
# This will config map will hold connection details that our container will use to authenticate to Conjur
apiVersion: v1
kind: ConfigMap
metadata:
  name: conjur-connect
  namespace: conjur
data:
  CONJUR_ACCOUNT: demo
  CONJUR_APPLIANCE_URL: "https://$CONJUR_FQDN"
  CONJUR_AUTHN_URL: "https://$CONJUR_FQDN/authn-jwt/k8s-cluster1"
  CONJUR_AUTHENTICATOR_ID: "k8s-cluster1"
  CONJUR_SSL_CERTIFICATE: |- 
$CONJUR_PUB_KEY