---
# This will config map will hold our script
apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-retrieve
  namespace: conjur
data:
  retrieve.sh: |
    #!/bin/bash
    JWT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    token=$(curl -k -s --request POST "$CONJUR_AUTHN_URL/demo/authenticate" --header 'Content-Type: application/x-www-form-urlencoded' --header "Accept-Encoding: base64" --data-urlencode "jwt=$JWT")
    secret=$(curl -k -s -X GET -H "Authorization: Token token=\"$token\"" "$CONJUR_APPLIANCE_URL/secrets/demo/variable/kubernetes/applications/safe/secret1")
    echo $secret
---
# Deployment for an application that consumes Conjur secrets using REST API bash script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-jwt-app1
  namespace: conjur
  labels:
    app: jwtsecrets
spec:
  replicas: 1
  selector:
    matchLabels:
      role: demo
      app: jwtsecrets
  template:
    metadata:
      labels:
        role: demo
        app: jwtsecrets
    spec:
      serviceAccountName: conjur-demo-acct
      containers:
      - name: k8s-jwt-app
        image: centos
        command: ["sleep","infinity"]
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: conjur-connect
        volumeMounts:
          - name: scripts
            mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: jwt-retrieve 
          defaultMode: 0755
