---
name: conjur-demo
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  push: 
    paths:
      - github-actions/**
jobs:
  fetch-secret-from-conjur:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: assafjh/conjur-action@test
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: demo
          authn_id: ${{ secrets.CONJUR_AUTHN_ID }}
          secrets: github/apps/safe/secret1|SECRET1;github/apps/safe/secret2|SECRET2;github/apps/safe/secret3|SECRET3
          certificate: ${{ secrets.CONJUR_PUBLIC_KEY }}
      - name : Echo secrets
        run: echo "Secret1 - $SECRET1 || Secret2 - $SECRET2 || Secret3 - $SECRET3"
